introduce cpe as a type, added validation for cpe check
interlynk-io/sbomqs pull request #32
Opened 2023-02-11 06:03 UTC by kchetans

2023-02-13 17:39 UTC, riteshnoronha requested changes

2023-02-13 17:39 UTC, riteshnoronha commented on pkg/sbom/spdx.go
> +			cpeValidae := cpe.NewCPE(p.Locator)
I believe this package only checks for valid 2.3 cpe not 2.2 can u clarify ?

2023-02-13 17:39 UTC, riteshnoronha commented on pkg/sbom/spdx.go
> +			cpeValidae := cpe.NewCPE(p.Locator)
lets rename cpeValidae to cpeV or something shorter.

2023-02-13 17:39 UTC, riteshnoronha commented on pkg/sbom/spdx.go
>  		if strings.ToLower(p.RefType) == spdx_common.TypeSecurityCPE23Type {
We need to add test cases for these functions.

2023-02-13 17:39 UTC, riteshnoronha commented on pkg/sbom/cdx.go
> +		ncpe := cpe.NewCPE(sc.CPE)
Need to add test cases

2023-02-13 17:39 UTC, riteshnoronha commented on pkg/cpe/cpe.go
> +const cpeRegex = ((`^([c][pP][eE]:/[AHOaho]?(:[A-Za-z0-9\._\-~%]*){0,6})`) +
Need 2.3 & 2.2 support

2023-02-14 15:03 UTC, kchetans commented on pkg/cpe/cpe.go
> +const cpeRegex = ((`^([c][pP][eE]:/[AHOaho]?(:[A-Za-z0-9\._\-~%]*){0,6})`) +
both cpe is validated this regex added test cases

2023-02-14 22:25 UTC, riteshnoronha approved these changes
Looks good to me, please remove the CPEMETA interface its not required.

2023-02-14 22:25 UTC, riteshnoronha commented on pkg/cpe/cpe.go
> +type CPEMeta interface {
There is no reason for interface.

2023-02-16 18:31 UTC, riteshnoronha submitted a review, later dismissed

2023-02-16 19:15 UTC, surendrapathak approved these changes
Squashed commit 
LGTM

2023-02-16 19:15 UTC, merged