19 configurable scoring criteria
interlynk-io/sbomqs pull request #75
Opened 2023-02-27 17:55 UTC by kchetans

scoring output customized by category or by feature, through config file or cmd line

eg. 
1. Through cmd line
./sbomqs score --filepath ./samples/sbomqs.cdx-modtool.json --feature doc-licence
SBOM Quality Score:0.0  components:14   ./samples/sbomqs.cdx-modtool.json
+----------+----------------------+----------+--------------------------------+
| CATEGORY |       FEATURE        |  SCORE   |              DESC              |
+----------+----------------------+----------+--------------------------------+
| Sharing  | Doc sharable license | 0.0/10.0 | doc has a sharable license     |
|          |                      |          | free 0 :: of 0                 |
+----------+----------------------+----------+--------------------------------+

2. Through config file
   a. Generate sbomqs config.yaml file
       eg../sbomqs generate
  b.  use the configuration file to enable through category and feature
       eg. ./sbomqs score --filepath ./samples/sbomqs.cdx-modtool.json --configpath config.yaml

2023-02-27 18:11 UTC, surendrapathak requested changes

2023-02-27 18:11 UTC, surendrapathak commented on config.yaml
> +      weight: 100
Please remove weights for this version because it has no impact

2023-02-27 18:11 UTC, surendrapathak commented on cmd/generate.go
> +const config_file_name = "config.yaml"
features.yaml instead of config.yaml (and same wiht variable name)

2023-02-27 18:11 UTC, surendrapathak commented on cmd/generate.go
> +	Use:   "generate",
Let's call it 

```sbomqs generate features ```

instead of 

```sbomqs generate```

2023-02-27 21:20 UTC, riteshnoronha requested changes

2023-02-27 21:20 UTC, riteshnoronha commented on cmd/generate.go
> +const config_file_name = "config.yaml"
rename to features.yaml

2023-02-27 21:20 UTC, riteshnoronha commented on features.yaml
> +category:
@kchetans  please remove this file.

2023-02-27 21:20 UTC, riteshnoronha commented on pkg/scorer/scorer.go
> +	for key, cr := range criteria {
This logic needs to be simplified, maybe split out the common functionality .

2023-02-28 18:23 UTC, riteshnoronha approved these changes

2023-02-28 20:58 UTC, surendrapathak commented on cmd/generate.go
> +Copyright © 2023 NAME HERE <EMAIL ADDRESS>
Fix Copyright for Interlynk

2023-02-28 21:00 UTC, surendrapathak approved these changes
Copyright will need fixes. The rest looks good to me.

2023-02-28 23:59 UTC, merged